services:

  app:
    build: .
    container_name: fx-notify-back
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./src:/usr/src/app/src"
      - "/usr/src/app/node_modules/"
