services:

  app:
    build: .
    container_name: fx-notify-back
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./src:/usr/src/app/src"
      - "/usr/src/app/node_modules/"


  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - "./redis_data:/data/"